services:
  opensearch:
    image: opensearchproject/opensearch:${OPENSEARCH_VERSION}
    container_name: ${NODE_NAME}
    environment:
      - cluster.name=${CLUSTER_NAME}
      - node.name=${NODE_NAME}
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS}
      - DISABLE_INSTALL_DEMO_CONFIG=${DISABLE_INSTALL_DEMO_CONFIG}
      - DISABLE_SECURITY_PLUGIN=${DISABLE_SECURITY_PLUGIN}
      - OPENSEARCH_PUBLISH_HOST=${OPENSEARCH_PUBLISH_HOST}
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile: { soft: 65536, hard: 65536 }
    volumes:
      - ${DATA_VOLUME_ROOT}/opensearch/data:/usr/share/opensearch/data
      - ${DATA_VOLUME_ROOT}/opensearch/logs:/usr/share/opensearch/logs
      - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./config/opensearch-performance-analyzer:/usr/share/opensearch/config/opensearch-performance-analyzer
    ports:
      - "${OPENSEARCH_BIND_ADDRESS}:${OPENSEARCH_PORT}:9200"
      - "${OPENSEARCH_BIND_ADDRESS}:${OPENSEARCH_DIAGNOSTICS_PORT}:9600"
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep '\"status\":\"green\"'"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  opensearch-net:
    driver: bridge
