# ------------------------------------------------------------------------------
# SECURITY SETTINGS
# ------------------------------------------------------------------------------

plugins.security.disabled: true

# ------------------------------------------------------------------------------
# NETWORKING
# ------------------------------------------------------------------------------

network.host: 0.0.0.0
transport.host: 0.0.0.0
transport.publish_host: ${OPENSEARCH_PUBLISH_HOST}

# ------------------------------------------------------------------------------
# SINGLE-NODE DISCOVERY SETTINGS (REQUIRED IN DOCKER)
# ------------------------------------------------------------------------------

discovery.type: single-node
