# Security settings
plugins.security.disabled: true

# Networking
network.host: 0.0.0.0
transport.host: 0.0.0.0
transport.publish_host: ${OPENSEARCH_PUBLISH_HOST}

# Single-node discovery settings (required in Docker)
discovery.type: single-node
